version: "3.7"
services:
  postgres:
    image: postgres:14.1
    container_name: capela_postgres
    environment:
      - POSTGRES_DB=capela
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/tmp/postgres/data
    ports:
      - 5432:5432
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: capela_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

  redis:
    image: redis
    container_name: capela_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

networks:
  rabbitmq_go_net:
    driver: bridge