info:
  app:
    name: Capela API
    version: @project.version@
    description: API para Inscrições de Eventos Espíritas.

server:
  port: 8080
  connection-timeout: 1800

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /manager

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/capela?useSSL=false
  cache:
    type: redis
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

capela:
  liquibase:
    clear-locks: true
    clear-sums: true
    main:
      enabled: true
      change-log: classpath:liquibase/schemas/public/schema-public-master.xml
    clients:
      enabled: true
      change-log: classpath:liquibase/schemas/common/schema-common-master.xml